/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @header      ...
 * @copyright   eosgarden 2011 - Jean-David Gadina <macmade@eosgarden.com>
 * @abstract    ...
 */

/*******************************************************************************
 * COPYRIGHT NOTICE
 * 
 * This file is based on the Reachability class, by Apple Inc.
 * The original file is licensed under the terms of the Apple Public Source
 * License (APSL).
 * 
 * http://www.opensource.apple.com/license/apsl/
 ******************************************************************************/

#import <netinet/in.h>
#import <SystemConfiguration/SystemConfiguration.h>

/*!
 * @typedef         ...
 * @abstract        ...
 * @description     ...
 */
typedef enum
{
	NetworkStatusNotReachable     = 0x00,
	NetworkStatusReachableViaWiFi = 0x01,
	NetworkStatusReachableViaWWAN = 0x02
}
NetworkStatus;

/*!
 * @var             ...
 * @abstract        ...
 * @description     ...
 */
FOUNDATION_EXPORT NSString * const NetworkReachabilityChangedNotification;

/*!
 * @var             ...
 * @abstract        ...
 * @description     ...
 */
FOUNDATION_EXPORT NSString * const ExceptionInvalidNetworkReachabilityInstance;

/*!
 * @class           NetworkReachability
 * @abstract        ...
 * @description     ...
 */
@interface NetworkReachability: NSObject
{
@protected
    
    /*!
     * @var             ...
     * @abstract        ...
     * @description     ...
     */
	BOOL _localWiFi;
	
    /*!
     * @var             ...
     * @abstract        ...
     * @description     ...
     */
    SCNetworkReachabilityRef _reachability;
    
@private
    
    /*!
     * @var             _NetworkReachability_Reserved
     * @abstract        Reserved instance variables
     * @description     Additional space for new instance variables, to
     *                  ensure binary compatibility with future version of
     *                  this class.
     */
    id _NetworkReachability_Reserved[ 5 ] __attribute__( ( unused ) );
}

/*!
 * @method          ...
 * @abstract        ...
 * @description     ...
 */
+ ( NetworkReachability * )networkReachabilityWithHostName: ( NSString * )hostName;

/*!
 * @method          ...
 * @abstract        ...
 * @description     ...
 */
+ ( NetworkReachability * )networkReachabilityWithAddress: ( const struct sockaddr_in * const )address;

/*!
 * @method          ...
 * @abstract        ...
 * @description     ...
 */
+ ( NetworkReachability * )networkReachabilityForInternetConnection;

/*!
 * @method          ...
 * @abstract        ...
 * @description     ...
 */
+ ( NetworkReachability * )networkReachabilityForLocalWiFi;

/*!
 * @method          ...
 * @abstract        ...
 * @description     ...
 */
- ( BOOL )startNotifier;

/*!
 * @method          ...
 * @abstract        ...
 * @description     ...
 */
- ( void )stopNotifier;

/*!
 * @method          ...
 * @abstract        ...
 * @description     ...
 */
- ( NetworkStatus )currentReachabilityStatus;

/*!
 * @method          ...
 * @abstract        ...
 * @description     ...
 */
- ( BOOL )connectionRequired;

@end


